#
# This file is part of phpFastCache.
#
# @license MIT License (MIT)
#
# For full copyright and license information, please see the docs/CREDITS.txt file.
#
# @author Georges.L (Geolim4)  <contact@geolim4.com>
# @author Contributors  https://github.com/PHPSocialNetwork/phpfastcache/graphs/contributors
#

build:
  dependencies:
    override:
      - "./bin/ci/scripts/install_dependencies.sh"
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override: [php-scrutinizer-run]
  environment: 
    php: 
      version: 8.0.0
      ini:
        date.timezone: 'Europe/Paris'
      pecl_extensions:
        - couchbase
        - redis
        - memcache
        - grpc
checks:
  php: true
coding_style: 
  php: 
    spaces: 
      around_operators: 
        concatenation: true
filter: 
  excluded_paths: 
    - .github/*
    - bin/*
    - docs/*
    - examples/*
    - var/*
    - vendor/*
    - tests/*
tools:
  external_code_coverage: false
  php_code_coverage: true
  php_code_sniffer: 
    config: 
      standard: PSR12
    enabled: true
    filter: 
      paths: 
        - lib/*
  php_mess_detector: 
    enabled: true
    filter: 
      paths: 
        - lib/*
